FROM python:3.11-slim

WORKDIR /app

# Copy backend requirements (since requirements.txt is inside backend)
COPY backend/requirements.txt requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy entire project
COPY . .

# Expose Streamlit port
EXPOSE 10000

# Run Streamlit from frontend folder
CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=10000", "--server.address=0.0.0.0"]