FROM python:3.10-slim

WORKDIR /app

COPY frontend/streamlit_app.py ./streamlit_app.py
COPY requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 10000

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=10000", "--server.address=0.0.0.0"]